services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: backend
    image: taskmanagment-backend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - taskmanagment-network

  frontend:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000/api
    container_name: frontend
    image: taskmanagment-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - taskmanagment-network

networks:
  taskmanagment-network:
    driver: bridge
